name: Unit Tests

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Decode Base64 Credentials
      run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 --decode >> cred.json

    - name: Test with pytest
      run: |
        pytest
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }} 
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }} 
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }} 
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} 
        GOOGLE_APPLICATION_CREDENTIALS: cred.json
        DISPLAY : '0'
